# Generated by Django 2.1.1 on 2018-09-21 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha2_code', models.CharField(max_length=2, unique=True)),
                ('alpha3_code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CountryRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='livegene.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('home_program', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_date', models.DateField()),
                ('total_budget', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=15)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organisations', to='livegene.Country')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('-end_date', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='PartnershipRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='livegene.Partnership')),
            ],
            options={
                'ordering': ('role_type',),
            },
        ),
        migrations.CreateModel(
            name='PartnershipRoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('home_program', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='livegene.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilri_code', models.CharField(max_length=55, unique=True)),
                ('full_name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('group', models.CharField(max_length=55)),
                ('donor_reference', models.CharField(max_length=55)),
                ('donor_project_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('capacity_development', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='livegene.Organisation')),
                ('principal_investigator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='livegene.Person')),
            ],
            options={
                'ordering': ('ilri_code',),
            },
        ),
        migrations.CreateModel(
            name='SamplingActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sampling_activities', to='livegene.Partnership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sampling_activities', to='livegene.Project')),
            ],
            options={
                'verbose_name_plural': 'sampling activities',
                'ordering': ('-end_date', '-start_date'),
            },
        ),
        migrations.CreateModel(
            name='SamplingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SamplingDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=15)),
                ('long_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('long_name',),
            },
        ),
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('link', models.URLField(unique=True)),
                ('logo_url', models.URLField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sustainable Development Goals',
                'verbose_name': 'Sustainable Development Goal',
                'ordering': ('headline', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='SDGRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_roles', to='livegene.Project')),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='livegene.SDG')),
            ],
        ),
        migrations.AddField(
            model_name='samplingdocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sampling_documents', to='livegene.SamplingDocumentType'),
        ),
        migrations.AddField(
            model_name='samplingdocument',
            name='sampling_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sampling_documents', to='livegene.SamplingActivity'),
        ),
        migrations.AddField(
            model_name='personrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='livegene.Project'),
        ),
        migrations.AddField(
            model_name='partnershiprole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_roles', to='livegene.Project'),
        ),
        migrations.AddField(
            model_name='partnershiprole',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles', to='livegene.PartnershipRoleType'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnerships', to='livegene.Person'),
        ),
        migrations.AddField(
            model_name='partnership',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnerships', to='livegene.Organisation'),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditures', to='livegene.Project'),
        ),
        migrations.AddField(
            model_name='countryrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_roles', to='livegene.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='sdgrole',
            unique_together={('project', 'sdg')},
        ),
        migrations.AlterUniqueTogether(
            name='personrole',
            unique_together={('project', 'person')},
        ),
        migrations.AlterUniqueTogether(
            name='countryrole',
            unique_together={('project', 'country')},
        ),
    ]
