# Generated by Django 2.1.1 on 2018-09-23 07:59

from django.db import migrations, models
import livegene.apps.livegene.validators


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0004_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[livegene.apps.livegene.validators.validate_lowercase]),
        ),
    ]
