# Generated by Django 2.1.1 on 2018-09-23 08:18

from django.db import migrations, models
import livegene.apps.livegene.validators


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0005_auto_20180923_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, validators=[livegene.apps.livegene.validators.validate_lowercase]),
        ),
    ]
