# Generated by Django 2.1.1 on 2018-09-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0007_auto_20180923_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='donor_project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
