# Generated by Django 2.1.1 on 2018-09-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0009_auto_20180923_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='donor_project_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='donor_reference',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
