# Generated by Django 2.1.1 on 2018-09-25 13:55

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0011_auto_20180925_0844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdg',
            options={'ordering': ('pk',), 'verbose_name': 'Sustainable Development Goal', 'verbose_name_plural': 'Sustainable Development Goals'},
        ),
        migrations.AlterField(
            model_name='sdg',
            name='color',
            field=colorfield.fields.ColorField(max_length=18),
        ),
        migrations.AlterField(
            model_name='sdg',
            name='logo_url',
            field=models.URLField(unique=True, verbose_name='Logo URL'),
        ),
    ]
