# Generated by Django 2.1.1 on 2018-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0013_auto_20180928_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnership',
            name='contact',
        ),
        migrations.AddField(
            model_name='partnership',
            name='contact',
            field=models.ManyToManyField(blank=True, related_name='partnerships', to='livegene.ContactPerson'),
        ),
    ]
