# Generated by Django 2.1.1 on 2018-09-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0014_auto_20180928_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
