# Generated by Django 2.1.1 on 2018-09-28 11:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0015_auto_20180928_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, unique=True),
        ),
    ]
