# Generated by Django 2.1.1 on 2018-10-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livegene', '0016_auto_20180928_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdgrole',
            options={'verbose_name': 'Sustainable Development Goal Role', 'verbose_name_plural': 'Sustainable Development Goal Roles'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='group',
            new_name='projects_group',
        ),
        migrations.AlterField(
            model_name='sdgrole',
            name='sdg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='livegene.SDG', verbose_name='Sustainable Development Goal'),
        ),
    ]
